### PR TITLE
Edit readme file (Lab 2)

### PR DESCRIPTION
**Pull request by deuzm**

### CODE REVIEW

**Comment by nastik1811** [comment]
As I understand, this should be a list of links 
image

**Comment by nastik1811** [comment]
This should be a list as well (a list of `div`s in this case)
image

**Review by nastik1811 — CHANGES_REQUESTED** [review]
The mockup looks good, but I'd like you to work a little on html-tags. I left you some comments here and in figma. Fix them and re-request the review

**Comment by deuzm** [comment]
Fixed, please rereview

**Review by nastik1811 — APPROVED** [review]

**Pull request merged**
